import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { Roboto } from "next/font/google";
import { ImprovedThemeProvider } from "@/context/improved-theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { getLocale, getMessages } from "next-intl/server";
import { ReactQueryProvider } from "@/react-query/provider";
import { Locale } from "@/services/locale";

// Initialize the new theme system on app start
import '@/lib/theme-utils';
const jakarta = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const locale = await getLocale();
  // Ensure that the incoming `locale` is valid
  // if (Locale   .locales.includes(locale as any)) {
  //   notFound();
  // }

  // Providing all messages to the client
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${jakarta.className} dark:bg-black antialiased`}>
        <NextThemesProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ImprovedThemeProvider>
            <NextIntlClientProvider messages={messages}>
              <ReactQueryProvider>{children}</ReactQueryProvider>
            </NextIntlClientProvider>
          </ImprovedThemeProvider>
        </NextThemesProvider>
      </body>
    </html>
  );
}
