import type { Metadata } from "next";
import "../globals.css";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { Roboto } from "next/font/google";
import ThemeDataProvider from "@/context/theme-data-provider";
import { NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { getLocale, getMessages } from "next-intl/server";
import { ReactQueryProvider } from "@/react-query/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const locale = await getLocale();
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={" dark:bg-black antialiased"}>
        <NextThemesProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ThemeDataProvider>
            <NextIntlClientProvider messages={messages}>
              <ReactQueryProvider>{children}</ReactQueryProvider>
            </NextIntlClientProvider>
          </ThemeDataProvider>
        </NextThemesProvider>
      </body>
    </html>
  );
}
